import Head from 'next/head'
import ImageGallery from 'react-image-gallery'

const images = [
	{
		original: 'https://picsum.photos/id/1018/1000/600/',
		thumbnail: 'https://picsum.photos/id/1018/250/150/',
	},
	{
		original: 'https://picsum.photos/id/1015/1000/600/',
		thumbnail: 'https://picsum.photos/id/1015/250/150/',
	},
	{
		original: 'https://picsum.photos/id/1019/1000/600/',
		thumbnail: 'https://picsum.photos/id/1019/250/150/',
	},
]

export default function Home() {
	return (
		<div>
			<Head>
				<title>Light cigarettes gallery</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			aaa
			<ImageGallery
				items={images}
				showThumbnails={false}
				showFullscreenButton={false}
				showPlayButton={false}
				showBullets
				showIndex
			/>
		</div>
	)
}
